kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: scenario-five-config
data:
  application.properties: |
    # Override the configuration properties here
    fhir.url1=hapi.fhir.org/baseDstu3/Patient/
    fhir.url2=hapi.fhir.org/baseDstu3/Condition
    server.host=scenario-five-scenario-five.apps.nashville.openshiftworkshop.com
    server.port=8080
    server.apiServerPort=80
    springfox.documentation.swagger.v2.path=/camel/api-doc